### ISSUE TITLE
TypeError: (0 , import_resolvers.BootstrapVueNextResolver) is not a function

### ISSUE THREAD

**Issue by hzxie** [bootstrap-vue/bootstrap-vue-next#923] opened 2023-02-11 02:02 UTC
**Describe the bug.** A clear and concise description of what the bug is.

```
➜  service-status git:(master) ✗ npm run dev                                      

> service-status@0.0.0 dev
> vite

failed to load config from /Users/hzxie/Development/service-status/vite.config.js
error when starting dev server:
TypeError: (0 , import_resolvers.BootstrapVueNextResolver) is not a function
    at Object.<anonymous> (/Users/hzxie/Development/service-status/vite.config.js:40:65)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at require.extensions.<computed> [as .js] (/Users/hzxie/Development/service-status/node_modules/vite/dist/node/chunks/dep-689425f3.js:62006:20)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfigFromBundledFile (/Users/hzxie/Development/service-status/node_modules/vite/dist/node/chunks/dep-689425f3.js:62014:17)
    at loadConfigFromFile (/Users/hzxie/Development/service-status/node_modules/vite/dist/node/chunks/dep-689425f3.js:61933:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce.** Steps to reproduce the behavior:

Install bootstrap-vue-next with the following steps

```
npm i bootstrap bootstrap-vue-next @popperjs/core
npm i unplugin-vue-components -D
```

Update `vite.config.js` as follows

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import { BootstrapVueNextResolver } from 'unplugin-vue-components/resolvers'

export default defineConfig({
  plugins: [
    vue(),
    Components({
      resolvers: [BootstrapVueNextResolver()]
    })
  ]
})
```

**Expected behavior.** A clear and concise description of what you expected to happen.

**Screenshots.** If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- OS: macOS 13.2
- Package Version: 0.7.3
- Npm/Yarn/Pnpm Version: npm@8.19.3

**Additional context.** Add any other context about the problem here.

**Comment by hzxie** [comment] 2023-02-11 02:05
Seems that duplicated with #883?

**Comment by VividLemon** [comment] 2023-02-11 02:05
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue-next/issues/883

That chat has a workaround. The official method can't be used until antfu approves the pr

**Closed by VividLemon** 2023-02-11 02:05 UTC
Labels: bug

**Comment by hzxie** [comment] 2023-02-11 02:09
@VividLemon 
Is there any other solution except waiting for upstream packages updating?

**Comment by VividLemon** [comment] 2023-02-11 02:10
> That chat has a workaround. The official method can't be used until antfu approves the pr

https://github.com/bootstrap-vue/bootstrap-vue-next/issues/883#issuecomment-1407687563
