### ISSUE TITLE
nuxt3 starter?

### ISSUE THREAD

**Issue by amery** [bootstrap-vue/bootstrap-vue-next#232] opened 2021-11-20 12:58 UTC
Hi, I'm new to the vue world and I'm trying to use nuxt3@latest + bootstrap-vue-3 (0.0.5) to generate static pages but I haven't found any documentation on how to get started

After some research
I took the base example page and added `<b-container/>` around it as follows:
```
<script lang="ts" setup>
    const counter = useState('counter', () => Math.round(Math.random() * 1000))
</script>

<template>
  <div>
    <b-container>
        Counter: {{ counter }}
        <button @click="counter++">+</button>
        <button @click="counter--">-</button>
    </b-container>
  </div>
</template>
```
and created a plugin based on what I saw on the README
```
import { defineNuxtPlugin } from '#app'

import BootstrapVue3 from 'bootstrap-vue-3'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(BootstrapVue3)
})
```

unfortunately, it crashes with something I don't really understand
> document is not defined

any pointer or suggestion? I'm pretty lost atm

**Comment by kwiksilver3441** [comment] 2021-11-23 15:28
The issue is that nuxt is by default server side rendered. This means that when the application starts out, it is on the server -- where "document" does not exist. You cannot access things like document.cookie, or other html specific objects. If your code does not include any reference to these objects, it's probably because both Nuxt3 and Bootstrap Vue 3 are both in alpha.

**Comment by xvaara** [comment] 2021-11-24 11:42
That is because bootstrap 5.1 isn't SSR compatible. 5.2 should be if they accept my pull request: https://github.com/twbs/bootstrap/pull/35339

If you need that now, install and build new dist (npm run dist) bootstrap from my branch: https://github.com/xvaara/bootstrap/tree/jo-ssr-friendly

and remove the one bootstrap-vue-3 installs. (in node_modules/bootstrap-vue-3/node_modules/bootstrap)

**Comment by lacorde** [comment] 2021-12-03 15:35
My code for importing BootstrapVue3 is the same exact as @amery, and results in the same error.

@xvaara Thank you for you help.
I still get `document is not defined` after removing bootstrap-vue-3's bootstrap and installing your fork.
Maybe I'm missing something in my nuxt.config.js entries ? Only css right now.

```
  css: [
    "~/node_modules/bootstrap/dist/css/bootstrap.min.css",
    "~/node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.css",
  ],
```

**Comment by kwiksilver3441** [comment] 2021-12-03 16:08
You should create a codepen

> My code for importing BootstrapVue3 is the same exact as @amery, and results in the same error.
> 
> @xvaara Thank you for you help. I still get `document is not defined` after removing bootstrap-vue-3's bootstrap and installing your fork. Maybe I'm missing something in my nuxt.config.js entries ? Only css right now.
> 
> ```
>   css: [
>     "~/node_modules/bootstrap/dist/css/bootstrap.min.css",
>     "~/node_modules/bootstrap-vue-3/dist/bootstrap-vue-3.css",
>   ],
> ```

**Comment by aceofwings** [comment] 2022-02-28 01:44
Bootstrap is still not ssr ready, therefore docs being build in ssr context fail.

**Comment by wobsoriano** [comment] 2022-03-13 09:35
This is my working setup for nuxt3:

```ts
// nuxt.config.ts
import { defineNuxtConfig } from "nuxt3"

export default defineNuxtConfig({
  css: [
    "bootstrap/dist/css/bootstrap.css",
    "bootstrap-vue-3/dist/bootstrap-vue-3.css",
  ],
})
```

```ts
// plugins/bootstrap.client.ts
import BootstrapVue3 from "bootstrap-vue-3"

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(BootstrapVue3)
})
```

```vue
<template>
  <div>
    <ClientOnly>
      <b-accordion>
        <b-accordion-item title="Accordion Item #1" visible>
          Accordion 1
        </b-accordion-item>
        <b-accordion-item title="Accordion Item #2">
          Accordion 2
        </b-accordion-item>
        <b-accordion-item title="Accordion Item #3">
          Accordion 3
        </b-accordion-item>
      </b-accordion>
    </ClientOnly>
  </div>
</template>
```

**Comment by edwh** [comment] 2022-04-03 07:34
@aceofwings, when you say Bootstrap is still not SSR-ready, are you talking about Bootstrap itself, or Bootstrap-Vue-3?  Either way, is there any indication of when that might happen?

(Background is that I'm coming from Nuxt2 / bootstrap-vue and looking at upgrading to Nuxt3 / bootstrap-vue-3 but I'm not on top of all the ecosystem state of play yet.)

**Comment by lessborders** [comment] 2022-04-03 20:08
@wobsoriano this still results in a document is undefined error - even without having used any of the components yet.

ReferenceError: document is not defined
    at C:\Users\MrBil\Documents\_lessborders\apps\lessborders.com\node_modules\bootstrap\js\dist\collapse.js:469:36

**Comment by wobsoriano** [comment] 2022-04-03 21:29
> @wobsoriano this still results in a document is undefined error - even without having used any of the components yet.
> 
> 
> 
> ReferenceError: document is not defined
> 
>     at C:\Users\MrBil\Documents\_lessborders\apps\lessborders.com\node_modules\bootstrap\js\dist\collapse.js:469:36

Would be nice to see your config and if you are wrapping the components in a <ClientOnly /> component

**Comment by xvaara** [comment] 2022-04-08 13:51
> @aceofwings, when you say Bootstrap is still not SSR-ready, are you talking about Bootstrap itself, or Bootstrap-Vue-3? Either way, is there any indication of when that might happen?

it's bootstrap it self. SSR friendly is coming in 5.2.  You can use my build of bootstrap (I use it in production) at https://github.com/xvaara/bootstrap to get ssr, but I haven't merged with the upstream in a while.

**Comment by eugen1j** [comment] 2022-04-09 20:28
@xvaara, I'm trying to set up nuxt3 + bootstrap-vue-3 + ssr using your `github:xvaara/bootstrap` package. Unfortunately, I got `window is not defined` error. In client-only mode (no ssr) it works well.

Here is my source https://github.com/eugen1j/nuxt3-bootstrap5

How can I fix this error? Thank you in advance.

**Comment by aceofwings** [comment] 2022-04-10 01:39
They have finally merged your request @xvaara ?

**Comment by xvaara** [comment] 2022-04-11 10:36
@aceofwings not yet: https://github.com/twbs/bootstrap/pull/34989

It should be in 5.2.

Or we can write the components without bootstrap.js, which I've done for a few components on my own fork.

**Comment by aceofwings** [comment] 2022-04-11 13:19
One day we will have a friendly ssr bootstrap... in the mean time I saw your discussion and anything with the use of directives and wrapping Bootstrap classes will have to be removed. 

Another option, which I explored for a while was to modify  the vite rollup compiler to patch or remove any document dependencies in addition to adding a Bootstrap SSR plugin. This was done more so that our docs will compile successfully. For example the BToast Docs are broken due to  some of the errors above. For now, Vite SSR is experimental and I have not found time to continue at the moment. Anything to do with SSR and Nuxt is not a priority for the project. As you mentioned writing the components without bootstrap.js dependencies are by far the fastest way to resolve this issue without jumping into low level SSR parsing.

**Comment by edwh** [comment] 2022-04-21 16:48
@xvaara Thanks for your reply.  I tried that fork, but I get `window is not defined` within Bootstrap code, e.g. in BCollapse:

`const requestAF = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.msRequestAnimationFrame || window`

Is this the kind of thing your changes are aimed at?

**Comment by xvaara** [comment] 2022-04-21 17:01
@edwh that is actually a faulty commit on released version of bootstrap-vue-3, it's fixed in #353 but it's not released yet. You need to wait or downgrade to previous release.

**Comment by edwh** [comment] 2022-04-21 18:12
@xvaara Brilliant.  With this I can get nuxt3 SSR working with bootstrap-vue-3.

```
"bootstrap": "git://github.com/xvaara/bootstrap.git",
"bootstrap-vue-3": "0.1.9",
```

You're all wonderful people and your hair is looking particularly lovely today.

**Comment by edwh** [comment] 2022-04-22 16:41
I also needed this:

```
  build: {
    // Need to transpile otherwise SSR fails.
    transpile: [/bootstrap-vue-3/],
  },

```  
...as per https://github.com/nuxt/framework/discussions/4523

**Comment by aceofwings** [comment] 2022-05-06 14:22
A new release covering SSR for nuxt has been released. Can we confirm that this solves the issue mentioned?

**Comment by edwh** [comment] 2022-05-08 09:53
@aceofwings Not for me yet - see https://github.com/cdmoro/bootstrap-vue-3/issues/364#issuecomment-1120386655

**Comment by dosstx** [comment] 2022-05-14 12:26
Bootstrap 5.2 was released yesterday. Did that change anything SSR related?

**Comment by edwh** [comment] 2022-05-14 13:00
@dosstx Not in a way that makes work (at least obviously).  If I install that release then I still see `document is not defined` SSR errors in Bootstrap itself:

```
  const enableDismissTrigger = (component, method = 'hide') => {
    const clickEvent = `click.dismiss${component.EVENT_KEY}`;
    const name = component.NAME;
    EventHandler__default.default.on(document, clickEvent, `[data-bs-dismiss="${name}"]`, function (event) {

```

**Comment by edwh** [comment] 2022-05-14 13:07
@xvaara, does that mean not all your fixes made it in?  Or that there is something new that needs fixing?

**Comment by xvaara** [comment] 2022-05-26 00:31
@edwh it seems the ssr fixes were postponed until 5.3.

**Comment by reqwire** [comment] 2022-05-26 12:36
> @edwh it seems the ssr fixes were postponed until 5.3.

Understandable too - the creator had a [heart attack.](https://twitter.com/mdo)

**Comment by mcartoixa** [comment] 2022-06-06 08:13
Do I understand that the bus factor is 1 on Bootstrap?

**Comment by birukg28** [comment] 2022-07-04 13:13
> 

is there working boilerplate?

**Comment by amery** [comment] 2022-10-15 22:56
@VividLemon would it be possible to have a maintained `ssr` branch here, same as `main` but using @xvaara's bootstrap fork? `@nuxt/kit` dependencies is needed too.

```diff
diff --git a/packages/bootstrap-vue-3/package.json b/packages/bootstrap-vue-3/package.json
index a76b71b3..a37000b3 100644
--- a/packages/bootstrap-vue-3/package.json
+++ b/packages/bootstrap-vue-3/package.json
@@ -39,6 +39,7 @@
     "vue": "^3.2.37"
   },
   "devDependencies": {
+    "@nuxt/kit": "3.0.0-rc.11",
     "@popperjs/core": "^2.11.6",
     "@types/bootstrap": "^5.2.2",
     "@vitejs/plugin-vue": "^3.0.0",
@@ -46,7 +47,7 @@
     "@vue/runtime-core": "^3.2.37",
     "@vue/shared": "^3.2.37",
     "@vue/test-utils": "^2.0.2",
-    "bootstrap": "^5.2.0",
+    "bootstrap": "github:xvaara/bootstrap",
     "c8": "^7.12.0",
     "jsdom": "^20.0.0",
     "rollup": "^2.78.1",
```

users of that branch would then need to:
```
pnpm add github:xvaara/bootstrap github.com:cdmoro/bootstrap-vue-3#ssr @popperjs/core
```

easy peasy :) and we can all carry on moving while we wait for bootstrap 5.3 without having to maintain our own forks :pray:

**Comment by VividLemon** [comment] 2022-10-15 23:06
> @VividLemon would it be possible to have a maintained `ssr` branch here, same as `main` but using @xvaara's bootstrap fork? `@nuxt/kit` dependencies is needed too.
> 
> ```diff
> diff --git a/packages/bootstrap-vue-3/package.json b/packages/bootstrap-vue-3/package.json
> index a76b71b3..a37000b3 100644
> --- a/packages/bootstrap-vue-3/package.json
> +++ b/packages/bootstrap-vue-3/package.json
> @@ -39,6 +39,7 @@
>      "vue": "^3.2.37"
>    },
>    "devDependencies": {
> +    "@nuxt/kit": "3.0.0-rc.11",
>      "@popperjs/core": "^2.11.6",
>      "@types/bootstrap": "^5.2.2",
>      "@vitejs/plugin-vue": "^3.0.0",
> @@ -46,7 +47,7 @@
>      "@vue/runtime-core": "^3.2.37",
>      "@vue/shared": "^3.2.37",
>      "@vue/test-utils": "^2.0.2",
> -    "bootstrap": "^5.2.0",
> +    "bootstrap": "github:xvaara/bootstrap",
>      "c8": "^7.12.0",
>      "jsdom": "^20.0.0",
>      "rollup": "^2.78.1",
> ```
> 
> users of that branch would then need to:
> 
> ```
> pnpm add github:xvaara/bootstrap github.com:cdmoro/bootstrap-vue-3#ssr @popperjs/core
> ```
> 
> easy peasy :) and we can all carry on moving while we wait for bootstrap 5.3 without having to maintain our own forks 🙏



> @VividLemon would it be possible to have a maintained `ssr` branch here, same as `main` but using @xvaara's bootstrap fork? `@nuxt/kit` dependencies is needed too.
> 
> ```diff
> diff --git a/packages/bootstrap-vue-3/package.json b/packages/bootstrap-vue-3/package.json
> index a76b71b3..a37000b3 100644
> --- a/packages/bootstrap-vue-3/package.json
> +++ b/packages/bootstrap-vue-3/package.json
> @@ -39,6 +39,7 @@
>      "vue": "^3.2.37"
>    },
>    "devDependencies": {
> +    "@nuxt/kit": "3.0.0-rc.11",
>      "@popperjs/core": "^2.11.6",
>      "@types/bootstrap": "^5.2.2",
>      "@vitejs/plugin-vue": "^3.0.0",
> @@ -46,7 +47,7 @@
>      "@vue/runtime-core": "^3.2.37",
>      "@vue/shared": "^3.2.37",
>      "@vue/test-utils": "^2.0.2",
> -    "bootstrap": "^5.2.0",
> +    "bootstrap": "github:xvaara/bootstrap",
>      "c8": "^7.12.0",
>      "jsdom": "^20.0.0",
>      "rollup": "^2.78.1",
> ```
> 
> users of that branch would then need to:
> 
> ```
> pnpm add github:xvaara/bootstrap github.com:cdmoro/bootstrap-vue-3#ssr @popperjs/core
> ```
> 
> easy peasy :) and we can all carry on moving while we wait for bootstrap 5.3 without having to maintain our own forks 🙏

Im working on removing bootstrap js outright, at which point ssr apps will be supported. As much as I enjoy your idea, I think it's a detour to fixing the real issue. 

If you or anyone wants to help, most bootstrap js basically handles transition states, which can be mostly handled by BTransition component. Some are obviously more complex

**Comment by amery** [comment] 2022-10-15 23:29
> Im working on removing bootstrap js outright, at which point ssr apps will be supported. As much as I enjoy your idea, I think it's a detour to fixing the real issue.

somehow I assumed you were invariably bound to bootstrap itself, but making it version-neutral sounds awesome

> 
> If you or anyone wants to help, most bootstrap js basically handles transition states, which can be mostly handled by BTransition component. Some are obviously more complex

I don't know much javascript but I'll follow your pointer and try to dive deeper

**Comment by VividLemon** [comment] 2022-10-15 23:41
https://github.com/cdmoro/bootstrap-vue-3/projects/5

**Comment by VividLemon** [comment] 2022-10-16 00:05
> somehow I assumed you were invariably bound to bootstrap itself

Bootstrap js is simply JS that's depressed because it's not Vue.

**Comment by xvaara** [comment] 2022-10-18 09:23
> https://github.com/cdmoro/bootstrap-vue-3/projects/5
> 
> Collapse is probably the easiest to start with. Though, in Vue's `<Transition>` component, it is difficult to have a class remain active after a transition has finished. Something Bootstrap does a lot with it's "show" class.

https://github.com/cdmoro/bootstrap-vue-3/discussions/324 I did some of the popperjs components for an earlier version. I could update them if required? But I was also thinking of using floating-ui instead of popperjs. Do we need to retain popperjs for compatibility or something?

**Comment by VividLemon** [comment] 2022-10-18 12:08
> > https://github.com/cdmoro/bootstrap-vue-3/projects/5
> > Collapse is probably the easiest to start with. Though, in Vue's `<Transition>` component, it is 
> In #324 I did some of the popperjs components for an earlier version. I could update them if required? But I was also thinking of using floating-ui instead of popperjs. Do we need to retain popperjs for compatibility or something? My disscussion about floating-ui: #355

I'd approve that change

**Comment by xvaara** [comment] 2022-10-19 12:41
> I'd approve that change

Which change? What are your opinions about changing to floating-ui?

**Comment by xvaara** [comment] 2022-11-11 10:33
@VividLemon hit me up on discord: `xvaara#2879` so we can chat about the floating-ui and writing out the bootstrap.js. I have so time next week, would like to coordinate with you.

**Closed** 2023-04-03 19:18 UTC
Labels: nuxt

**Comment by maxvanweenen** [comment] 2023-04-19 09:39
To answer the original question, there isn't really a reason to use bootstrap-vue anymore. You can just use bootstrap 5 since it doesn't use jQuery. Getting bootstrap 5 to work with Nuxt 3 and having it compile nice and fast can be a bit of a pain, but I made a optimised starter a while back that does it all for you. 

So if anybody just want to run nuxt 3 with bootstrap 5 here it is:
[https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter](https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter)

**Comment by VividLemon** [comment] 2023-04-19 10:16
> To answer the original question, there isn't really a reason to use bootstrap-vue anymore. You can just use bootstrap 5 since it doesn't use jQuery. Getting bootstrap 5 to work with Nuxt 3 and having it compile nice and fast can be a bit of a pain, but I made a optimised starter a while back that does it all for you.
> 
> So if anybody just want to run nuxt 3 with bootstrap 5 here it is: https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter

Umm. No? Bootstrap js uses Window & Document in every component that requires js.

So, have fun with that

**Comment by maxvanweenen** [comment] 2023-04-19 12:14
> > To answer the original question, there isn't really a reason to use bootstrap-vue anymore. You can just use bootstrap 5 since it doesn't use jQuery. Getting bootstrap 5 to work with Nuxt 3 and having it compile nice and fast can be a bit of a pain, but I made a optimised starter a while back that does it all for you.
> > So if anybody just want to run nuxt 3 with bootstrap 5 here it is: https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter
> 
> Umm. No? Bootstrap js uses Window & Document in every component that requires js.
> 
> So, have fun with that

We might be misunderstanding each other, but Window and Document aren't jQuery but native JS and bootstrap 5 runs perfectly fine in Vue projects like Nuxt. If you check out the project in my earlier link you will see bootstrap 5 (including the JS components) work like a charm in a Nuxt 3 project. So there isn't a reason to use bootstrap-vue unless you really prefer the <b-container> syntax vs <div class="container">

**Comment by VividLemon** [comment] 2023-04-19 12:43
No SSR app works fine when using window. Perhaps you don't know enough about  SSR. There is no window object on the server

**Comment by maxvanweenen** [comment] 2023-04-19 12:59
> No SSR app works fine when using window. Perhaps you don't know enough about SSR. There is no window object on the server

Ah two things:
1. the original question I am responding was not asking about SSR. 
2. Just out of interest I tried running the package from my link on SSR and using a dropdown and it seems like they fixed the problem you are referencing. As far as I can tell they changed it in the last version 5.2.

**Comment by VividLemon** [comment] 2023-04-19 13:01
![Screenshot_20230419-080047](https://user-images.githubusercontent.com/31498096/233082704-e91fe4db-ce1f-4b08-9945-1bc8cdacf885.png)
No, they just render bootstrap in client only mode

**Comment by maxvanweenen** [comment] 2023-04-19 13:11
That might explain it. Would still be worth to check if they still use document and window in 5.2. 

But I'll change my answer then to:
You can use this [starter template](https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter) to run bootstrap 5 in Nuxt and you don't need boostrap-vue. UNLESS: you want to run in SSR, that might not work (I did not test this). In that edge case you could try bootstrap-vue.

**Comment by VividLemon** [comment] 2023-04-19 13:33
> That might explain it. Would still be worth to check if they still use document and window in 5.2.

I guarantee you that if Bootstrap made attempts to become SSR friendly, I would know about it.

> You can use this [starter template](https://github.com/maxvanweenen/Nuxt-3-bootstrap-5-starter) to run bootstrap 5 in Nuxt and you don't need boostrap-vue. UNLESS: you want to run in SSR, that might not work (I did not test this). In that edge case you could try bootstrap-vue.

There is any argument to be made for being "traditional". Obviously one could write Bootstrap manually, it would work just fine in most cases. But there is more reasoning to using Bootstrap-vue. Components syntax is less verbose, and as such, is easier to maintain, especially for very complex applications. You could solve this by wrapping your own Bootstrap components in Vue components, but that's already done here. The goal is to translate the library in a Vue friendly library. Of course, in this case, I'd consider it a requirement for SSR, as using it in client only defeats the purpose of SSR. Of course, this took significant time to achieve, and SSR has not been supported up until recently, but it's complicated to achieve. I don't think "If you want to run SSR" is an "edge case", it's one of the main pillars to using Nuxt.
